---
server:
  ingress:
    enabled: true
    hostname: argocd.nice.local
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # extraPortMappings:
    #   - --insecure
