hostname: rancher.nice.local

ingress:
  enabled: true
  ingressClassName: nginx
  extraAnnotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
