apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - svc.yaml

commonLabels:
  company: happy_corp
  app: node-app

commonAnnotations:
  description: "This is a test deployment"
